name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.13.1

  # Core packages installed via conda
  - numpy=2.2.2
  - pandas=2.2.3
  - matplotlib=3.10.0
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - pillow=11.1.0
  - tqdm=4.67.1
  - joblib=1.4.2
  - jupyterlab=4.3.5
  - ipython=8.32.0
  - jinja2=3.1.5
  - protobuf=5.29.3
  - pytorch=2.5.1
  - torchvision  # Add if required for PyTorch
  - torchaudio  # Add if required for PyTorch
  - folium=0.19.4
  - fsspec=2025.2.0
  - sentence-transformers  # Available on conda-forge
  - h3  # Install via pip; not available on Conda

  # Utilities
  - requests=2.32.3
  - streamlit=1.42.0
  - streamlit-folium=0.24.0
  - wordcloud=1.9.4
  - pyzmq=26.2.1
  - altair=5.5.0
  - six=1.17.0
  - python-dateutil=2.9.0.post0

  # Additional dependencies
  - importlib-metadata=8.6.1
  - typing-extensions=4.12.2
  - typing-utils=0.1.0
  - regex=2024.11.6
  - markdown-it-py=3.0.0
  - matplotlib-inline=0.1.7

  # System dependencies
  - ca-certificates
  - pip

  # Pip dependencies
  - pip:
      - h3
      - gitpython==3.1.44
      - tenacity==9.0.0
      - rich==13.9.4
      - smmap==5.0.2
